//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./MatlabParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="MatlabParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IMatlabParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MatlabParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] MatlabParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MatlabParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] MatlabParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MatlabParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] MatlabParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MatlabParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] MatlabParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MatlabParser.functionDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDecl([NotNull] MatlabParser.FunctionDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MatlabParser.functionDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDecl([NotNull] MatlabParser.FunctionDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MatlabParser.returnVars"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnVars([NotNull] MatlabParser.ReturnVarsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MatlabParser.returnVars"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnVars([NotNull] MatlabParser.ReturnVarsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MatlabParser.paramList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParamList([NotNull] MatlabParser.ParamListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MatlabParser.paramList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParamList([NotNull] MatlabParser.ParamListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MatlabParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStatement([NotNull] MatlabParser.IfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MatlabParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStatement([NotNull] MatlabParser.IfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MatlabParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForStatement([NotNull] MatlabParser.ForStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MatlabParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForStatement([NotNull] MatlabParser.ForStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MatlabParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileStatement([NotNull] MatlabParser.WhileStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MatlabParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileStatement([NotNull] MatlabParser.WhileStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MatlabParser.assignStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignStatement([NotNull] MatlabParser.AssignStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MatlabParser.assignStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignStatement([NotNull] MatlabParser.AssignStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MatlabParser.lvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLvalue([NotNull] MatlabParser.LvalueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MatlabParser.lvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLvalue([NotNull] MatlabParser.LvalueContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>eqExpr</c>
	/// labeled alternative in <see cref="MatlabParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEqExpr([NotNull] MatlabParser.EqExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>eqExpr</c>
	/// labeled alternative in <see cref="MatlabParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEqExpr([NotNull] MatlabParser.EqExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>notExpr</c>
	/// labeled alternative in <see cref="MatlabParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNotExpr([NotNull] MatlabParser.NotExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>notExpr</c>
	/// labeled alternative in <see cref="MatlabParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNotExpr([NotNull] MatlabParser.NotExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>primaryExpr</c>
	/// labeled alternative in <see cref="MatlabParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimaryExpr([NotNull] MatlabParser.PrimaryExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>primaryExpr</c>
	/// labeled alternative in <see cref="MatlabParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimaryExpr([NotNull] MatlabParser.PrimaryExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>addExpr</c>
	/// labeled alternative in <see cref="MatlabParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddExpr([NotNull] MatlabParser.AddExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>addExpr</c>
	/// labeled alternative in <see cref="MatlabParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddExpr([NotNull] MatlabParser.AddExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>unaryMinus</c>
	/// labeled alternative in <see cref="MatlabParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryMinus([NotNull] MatlabParser.UnaryMinusContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>unaryMinus</c>
	/// labeled alternative in <see cref="MatlabParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryMinus([NotNull] MatlabParser.UnaryMinusContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>mulExpr</c>
	/// labeled alternative in <see cref="MatlabParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMulExpr([NotNull] MatlabParser.MulExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>mulExpr</c>
	/// labeled alternative in <see cref="MatlabParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMulExpr([NotNull] MatlabParser.MulExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>orExpr</c>
	/// labeled alternative in <see cref="MatlabParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrExpr([NotNull] MatlabParser.OrExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>orExpr</c>
	/// labeled alternative in <see cref="MatlabParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrExpr([NotNull] MatlabParser.OrExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>relExpr</c>
	/// labeled alternative in <see cref="MatlabParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelExpr([NotNull] MatlabParser.RelExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>relExpr</c>
	/// labeled alternative in <see cref="MatlabParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelExpr([NotNull] MatlabParser.RelExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>powExpr</c>
	/// labeled alternative in <see cref="MatlabParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPowExpr([NotNull] MatlabParser.PowExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>powExpr</c>
	/// labeled alternative in <see cref="MatlabParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPowExpr([NotNull] MatlabParser.PowExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>rangeExpr</c>
	/// labeled alternative in <see cref="MatlabParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRangeExpr([NotNull] MatlabParser.RangeExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>rangeExpr</c>
	/// labeled alternative in <see cref="MatlabParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRangeExpr([NotNull] MatlabParser.RangeExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>andExpr</c>
	/// labeled alternative in <see cref="MatlabParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAndExpr([NotNull] MatlabParser.AndExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>andExpr</c>
	/// labeled alternative in <see cref="MatlabParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAndExpr([NotNull] MatlabParser.AndExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MatlabParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimary([NotNull] MatlabParser.PrimaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MatlabParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimary([NotNull] MatlabParser.PrimaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MatlabParser.argList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgList([NotNull] MatlabParser.ArgListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MatlabParser.argList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgList([NotNull] MatlabParser.ArgListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MatlabParser.matrixRows"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMatrixRows([NotNull] MatlabParser.MatrixRowsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MatlabParser.matrixRows"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMatrixRows([NotNull] MatlabParser.MatrixRowsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MatlabParser.matrixRow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMatrixRow([NotNull] MatlabParser.MatrixRowContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MatlabParser.matrixRow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMatrixRow([NotNull] MatlabParser.MatrixRowContext context);
}
